#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ergodox_pretty(
    //┌────────┬────────────┬─────────────────┬─────────────┬─────────────┬──────┬────────────┐                   ┌────────────┬─────┬─────────────┬─────────────┬─────────────┬────────────────┬────────┐
        KC_GRV,         KC_1,             KC_2,         KC_3,         KC_4, KC_5,       KC_ESC,                           TT(1), KC_6,         KC_7,         KC_8,         KC_9,            KC_0, KC_MINS, 
    //├────────┼────────────┼─────────────────┼─────────────┼─────────────┼──────┼────────────┤                   ├────────────┼─────┼─────────────┼─────────────┼─────────────┼────────────────┼────────┤
         KC_TAB,        KC_Q,             KC_W,         KC_E,         KC_R, KC_T,        TO(0),                           TO(2), KC_Y,        KC_U,          KC_I,         KC_O,            KC_P, KC_BSLS, 
    //├────────┼────────────┼─────────────────┼─────────────┼─────────────┼──────┤            |                   |            ├─────┼─────────────┼─────────────┼─────────────┼────────────────┼────────┤
        KC_CAPS, LSFT_T(KC_A),    LCTL_T(KC_S), LGUI_T(KC_D), LALT_T(KC_F), KC_G,                                                KC_H, RALT_T(KC_J), RGUI_T(KC_K), RCTL_T(KC_L), RSFT_T(KC_SCLN), KC_QUOT, 
    //├────────┼────────────┼─────────────────┼─────────────┼─────────────┼──────┼────────────┤                   ├────────────┼─────┼─────────────┼─────────────┼─────────────┼────────────────┼────────┤
        KC_LSFT,        KC_Z,             KC_X,         KC_C,         KC_V,  KC_B,       TO(1),                           TO(3), KC_N,         KC_M,      KC_COMM,       KC_DOT,         KC_SLSH,  KC_EQL, 
    //├────────┼────────────┼─────────────────┼─────────────┼─────────────┼──────┴────────────┘                   └────────────┴─────┼─────────────┼─────────────┼─────────────┼────────────────┼────────┤
        KC_RSFT,     KC_QUOT,          KC_RALT,      KC_LBRC,      KC_RBRC,                                                                 KC_LEFT,      KC_DOWN,        KC_UP,        KC_RIGHT,   TO(0),
    //└────────┴────────────┴─────────────────┴─────────────┴─────────────┘                                                          └─────────────┴─────────────┴─────────────┴────────────────┴────────┘
    //                                                                ┌─────────────┬──────────────┐     ┌────────────┬─────────────┐
                                                                       LT(1,KC_RALT), LT(2,KC_PSCR),      LT(2,KC_INS), LT(1,KC_DEL),
    //                                                       ┌────────┼─────────────┼──────────────┤     ├────────────┼─────────────┼────────┐ 
                                                                                            KC_HOME,           KC_PGUP,
    //                                                       |        |             ├──────────────┤     ├────────────┤             |        | 
                                                                KC_SPC,      KC_BSPC,        KC_END,           KC_PGDN,       KC_TAB,  KC_ENT
    //                                                       └────────┴─────────────┴──────────────┘     └────────────┴─────────────┴────────┘
      ),
	[1] = LAYOUT_ergodox_pretty(
    //┌────────┬────────┬────────┬────────┬────────┬────────┬────────┐         ┌────────┬────────┬────────┬────────┬────────┬────────┬────────┐
          KC_NO,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,             KC_F7,   KC_F8,   KC_F9,  KC_F10,  KC_F11,  KC_F12, KC_TRNS, 
    //├────────┼────────┼────────┼────────┼────────┼────────┼────────┤         ├────────┼────────┼────────┼────────┼────────┼────────┼────────┤
        KC_TRNS, KC_EXLM,   KC_AT, KC_LCBR, KC_RCBR, KC_PIPE, KC_TRNS,           KC_TRNS,   KC_P7,   KC_P8,   KC_P9, KC_PSLS, KC_TRNS, KC_TRNS,
    //├────────┼────────┼────────┼────────┼────────┼────────┤        |         |        ├────────┼────────┼────────┼────────┼────────┼────────┤
        KC_TRNS, KC_HASH,  KC_DLR, KC_LPRN, KC_RPRN, KC_GRV,                                KC_P4,   KC_P5,   KC_P6, KC_PAST, KC_TRNS, KC_TRNS,
    //├────────┼────────┼────────┼────────┼────────┼────────┼────────┤         ├────────┼────────┼────────┼────────┼────────┼────────┼────────┤
        KC_TRNS, KC_PERC, KC_CIRC, KC_LBRC, KC_RBRC, KC_TILD, KC_TRNS,           KC_TRNS,   KC_P1,   KC_P2,   KC_P3, KC_PMNS, KC_PEQL, KC_TRNS, 
    //├────────┼────────┼────────┼────────┼────────┼────────┴────────┘         └────────┴────────┼────────┼────────┼────────┼────────┼────────┤
        EEP_RST, KC_AMPR, KC_TRNS, KC_TRNS, KC_TRNS,                                                 KC_P0, KC_PDOT, KC_PPLS, KC_PENT,   TO(0),
    //└────────┴────────┴────────┴────────┴────────┘                                             └────────┴────────┴────────┴────────┴────────┘
    //                                               ┌────────┬────────┐     ┌────────┬────────┐
                                                       RGB_MOD, KC_TRNS,       RGB_TOG, RGB_M_P,
    //                                      ┌────────┼────────┼────────┤     ├────────┼────────┼────────┐ 
                                                                RGB_VAI,       RGB_HUI,
    //                                      |        |        ├────────┤     ├────────┤        |        | 
                                              KC_TRNS, KC_TRNS, RGB_VAD,       RGB_HUD, KC_TRNS, KC_TRNS
    //                                      └────────┴────────┴────────┘     └────────┴────────┴────────┘
      ),
	[2] = LAYOUT_ergodox_pretty(
    //┌────────┬────────┬────────┬────────┬────────┬────────┬────────┐         ┌────────┬────────┬────────┬────────┬────────┬────────┬────────┐
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,           KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    //├────────┼────────┼────────┼────────┼────────┼────────┼────────┤         ├────────┼────────┼────────┼────────┼────────┼────────┼────────┤
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,           KC_TRNS, KC_HOME, KC_PGDN, KC_PGUP,  KC_END, KC_TRNS, KC_TRNS,
    //├────────┼────────┼────────┼────────┼────────┼────────┤        |         |        ├────────┼────────┼────────┼────────┼────────┼────────┤
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                             KC_LEFT, KC_DOWN,   KC_UP, KC_RGHT, KC_TRNS, KC_MPLY,
    //├────────┼────────┼────────┼────────┼────────┼────────┼────────┤         ├────────┼────────┼────────┼────────┼────────┼────────┼────────┤
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,           KC_TRNS, KC_TRNS, KC_TRNS, KC_MPRV, KC_MNXT, KC_TRNS, KC_TRNS,
    //├────────┼────────┼────────┼────────┼────────┼────────┴────────┘         └────────┴────────┼────────┼────────┼────────┼────────┼────────┤
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                                               KC_VOLU, KC_VOLD, KC_MUTE, KC_TRNS,   TO(0),
    //└────────┴────────┴────────┴────────┴────────┘                                             └────────┴────────┴────────┴────────┴────────┘
    //                                               ┌────────┬────────┐     ┌────────┬────────┐
                                                       KC_TRNS, KC_TRNS,       KC_TRNS, KC_TRNS,
    //                                      ┌────────┼────────┼────────┤     ├────────┼────────┼────────┐ 
                                                                KC_TRNS,       KC_TRNS,
    //                                      |        |        ├────────┤     ├────────┤        |        | 
                                              KC_TRNS, KC_TRNS, KC_TRNS,       KC_TRNS, KC_TRNS, KC_WBAK
    //                                      └────────┴────────┴────────┘     └────────┴────────┴────────┘
      ),
	[3] = LAYOUT_ergodox_pretty(
    //┌────────┬────────┬────────┬────────┬────────┬────────┬────────┐         ┌────────┬────────┬────────┬────────┬────────┬────────┬────────┐
          KC_NO,    KC_1,    KC_2,    KC_3,    KC_4,    KC_5,   KC_NO,             KC_NO,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,   KC_NO, 
    //├────────┼────────┼────────┼────────┼────────┼────────┼────────┤         ├────────┼────────┼────────┼────────┼────────┼────────┼────────┤
         KC_TAB,    KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,   KC_NO,             KC_NO,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P, KC_BSLS, 
    //├────────┼────────┼────────┼────────┼────────┼────────┤        |         |        ├────────┼────────┼────────┼────────┼────────┼────────┤
          KC_NO,    KC_A,    KC_S,    KC_D,    KC_F,    KC_G,                                KC_H,    KC_J,    KC_K,    KC_L, KC_SCLN, KC_QUOT,
    //├────────┼────────┼────────┼────────┼────────┼────────┼────────┤         ├────────┼────────┼────────┼────────┼────────┼────────┼────────┤
          KC_NO,    KC_Z,    KC_X,    KC_C,    KC_V,    KC_B, KC_TRNS,           KC_TRNS,    KC_N,    KC_M, KC_COMM,  KC_DOT, KC_SLSH,   KC_NO,
    //├────────┼────────┼────────┼────────┼────────┼────────┴────────┘         └────────┴────────┼────────┼────────┼────────┼────────┼────────┤
          KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,                                                 KC_NO,   KC_NO,   KC_NO,   KC_NO, KC_TRNS,
    //└────────┴────────┴────────┴────────┴────────┘                                             └────────┴────────┴────────┴────────┴────────┘
    //                                               ┌────────┬────────┐     ┌────────┬────────┐
                                                       KC_TRNS, KC_TRNS,       KC_TRNS, KC_TRNS,
    //                                      ┌────────┼────────┼────────┤     ├────────┼────────┼────────┐ 
                                                                KC_TRNS,       KC_TRNS,
    //                                      |        |        ├────────┤     ├────────┤        |        | 
                                              KC_TRNS, KC_TRNS, KC_TRNS,       KC_TRNS, KC_TRNS, KC_TRNS
    //                                      └────────┴────────┴────────┘     └────────┴────────┴────────┘
      )
};


// Runs just one time when the keyboard initializes.
void keyboard_post_init_user(void) {
#ifdef RGBLIGHT_COLOR_LAYER_0
  rgblight_setrgb(RGBLIGHT_COLOR_LAYER_0);
#endif
};


// Runs whenever there is a layer state change.
layer_state_t layer_state_set_user(layer_state_t state) {
 ergodox_board_led_off();
 ergodox_right_led_1_off();
 ergodox_right_led_2_off();
 ergodox_right_led_3_off();

 uint8_t layer = get_highest_layer(state);
 switch (layer) {
     case 0:
       ergodox_right_led_1_on();
       #ifdef RGBLIGHT_COLOR_LAYER_0
         rgblight_setrgb(RGBLIGHT_COLOR_LAYER_0);
       #endif
       break;
     case 1:
       ergodox_right_led_2_on();
       #ifdef RGBLIGHT_COLOR_LAYER_1
         rgblight_setrgb(RGBLIGHT_COLOR_LAYER_1);
       #endif
       break;
     case 2:
       ergodox_right_led_3_on();
       #ifdef RGBLIGHT_COLOR_LAYER_2
         rgblight_setrgb(RGBLIGHT_COLOR_LAYER_2);
       #endif
       break;
     case 3:
       ergodox_right_led_1_on();
       ergodox_right_led_2_on();
       #ifdef RGBLIGHT_COLOR_LAYER_3
         rgblight_setrgb(RGBLIGHT_COLOR_LAYER_3);
       #endif
       break;
     case 4:
       ergodox_right_led_1_on();
       ergodox_right_led_2_on();
       ergodox_right_led_3_on();
       #ifdef RGBLIGHT_COLOR_LAYER_4
         rgblight_setrgb(RGBLIGHT_COLOR_LAYER_4);
       #endif
       break;
     case 5:
       ergodox_right_led_1_on();
       ergodox_right_led_3_on();
       #ifdef RGBLIGHT_COLOR_LAYER_5
         rgblight_setrgb(RGBLIGHT_COLOR_LAYER_5);
       #endif
       break;
     case 6:
       ergodox_right_led_2_on();
       ergodox_right_led_3_on();
       #ifdef RGBLIGHT_COLOR_LAYER_6
         rgblight_setrgb(RGBLIGHT_COLOR_LAYER_6);
       #endif
       break;
     case 7:
       ergodox_right_led_1_on();
       ergodox_right_led_2_on();
       ergodox_right_led_3_on();
       #ifdef RGBLIGHT_COLOR_LAYER_7
         rgblight_setrgb(RGBLIGHT_COLOR_LAYER_7);
       #endif
       break;
     default:
       break;
   }

 return state;
};

